### ISSUE TITLE
[Update] blog with folder (Level-1) based categories

### ISSUE THREAD

**Issue by Pk13055** [Synalytica/synalytica.github.io#11]
We need to have the ability to create folders (just 1 level deep, _for now_) so that the blogs are automatically sorted.

**Comment by MysterTech** [comment]
Can be done using the permalink property in blog post metadata like below :

```
permalink : /blog/[folder name]/:title
```

**Comment by MysterTech** [comment]
No code change needed. The metadata can be added to the posts which automatically will generate to required folder. Jekyll engine takes the permalink and writes source files to expected location.

**Comment by Pk13055** [comment]
@MysterTech can you move the hello-world into the dev category folder and show us with an example?

**Comment by MysterTech** [comment]
Have added new changes to the blog-folder-demo branch. Kindly deploy from the branch to see changes.

**Comment by Pk13055** [comment]
I took a look, kindly create a PR for the same so that we can get it merged!

**Comment by Pk13055** [comment]
Fixed as of 204f22b8654b0cdcfdad4de630c29fbdb609cf9a
